--- #YAML:1.0
name:               Catalyst-View-SVG-TT-Graph
version:            0.0223
abstract:           SVG::TT::Graph charts (in svg/png/gif/jpeg..) for your Catalyst application
author:
    - Terence Monteiro <terencemo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Plugin::ConfigLoader:  0.23
    Catalyst::Plugin::Static::Simple:  0.01
    Catalyst::Runtime:    5.80001
    FindBin:              1.42
    Image::LibRSVG:       0.07
    MIME::Types:          1.30
    Moose:                1.09
    namespace::autoclean:  0.09
    SVG::TT::Graph:       0.14
    Test::More:           0.94
    Test::WWW::Mechanize::Catalyst:  0.52
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
