--- #YAML:1.0
name:               Catalyst-View-SVG-TT-Graph
version:            0.01
abstract:           SVG::TT::Graph charts (in svg/png/jpeg.. format) for your Catalyst application
author:
    - Terence Monteiro <terencemo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            1.11
    Image::LibRSVG:  0.07
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
